### PR TITLE
#3 simplify GHA configuration

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #3

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Waiting for https://github.com/rake-compiler/rake-compiler/pull/166 to be released (otherwise, we need to cross-compile everything from macOS)

I will prepare a cross-compile variant yet

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by alexeymorozov** [comment]
👍 

Just for information. Also there is ffi-compiler, may be it can cross-compile, as in [libmspack](https://github.com/davispuh/ruby-libmspack/blob/master/ext/Rakefile)

**Comment by CAMOBAP** [comment]
@alexeymorozov unfortunatelly it doesn't help with platform gem generation

Globally I considered those options:

  - [?] use rake-compiler
    [+] easy build/publish gems
    [-] workaround for ffi_lib name lookup
    [-] missing export on windows
  - [?] use own solution (own Makefile)
    [+] no workarounds
    [-] need to implement it
    [-] need to maintain it
    [-] doesn't help here https://github.com/ffi/ffi-compiler

I still trying to adapt `rake-compiler` to be used with our `Makefile`

**Comment by CAMOBAP** [comment]
@alexeymorozov @ronaldtse could you please review it, I need to merge it to do end-to-end testing

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Pull request merged**
